# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'LEIFR' do

pod 'FontAwesome+iOS'
pod 'FontBlaster'
pod 'wkb-ios'

end

target 'LEIFRTests' do
	
pod 'wkb-ios'

end
