# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'LEIFR' do

pod 'FontBlaster'
pod 'wkb-ios'
pod 'RealmSwift', '2.0.3'
pod 'UICircularProgressRing'

end

target 'LEIFRTests' do
	
pod 'wkb-ios'
pod 'RealmSwift', '2.0.3'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
