# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LEIFR' do

pod 'wkb-ios'
pod 'RealmSwift'

end

target 'LEIFRTests' do

pod 'RealmSwift'

end